//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Campus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int ects { get; set; }
        public string courseName { get; set; }
        public string courseCode { get; set; }
        public Nullable<int> numHours { get; set; }
        public string preReqCourseCode { get; set; }
    }
}
