//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Campus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public System.DateTime date { get; set; }
        public string semester { get; set; }
        public string courseCode { get; set; }
        public int yearr { get; set; }
        public int sectionId { get; set; }
        public string ename { get; set; }
        public string issn { get; set; }
    }
}
