//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Campus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public string ssn { get; set; }
        public string iName { get; set; }
        public string rankk { get; set; }
        public int baseSalary { get; set; }
        public Nullable<int> extraSalary { get; set; }
        public string dName { get; set; }
    }
}
