//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Campus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prevDegrees
    {
        public string college { get; set; }
        public string degree { get; set; }
        public int year { get; set; }
        public string gradsssn { get; set; }
    }
}
