//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Campus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string leadSsn { get; set; }
        public string prName { get; set; }
        public Nullable<int> budget { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string subject { get; set; }
        public string contrDName { get; set; }
    }
}
