//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Campus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string sssn { get; set; }
        public bool gradorUgrad { get; set; }
        public string advisorSsn { get; set; }
        public string currCode { get; set; }
        public string sName { get; set; }
        public string studentId { get; set; }
    }
}
